function on_mcm_load()
  return { id="ammo", sh=true, gr={   
      { id="header", type="slide", link="ui_options_slider_economy_diff", text="ui_mcm_dph_loot_cond_ammo", size= {512,50}, spacing=20 },
      { id="disable_bad", type="check", val=1, def=true},
      { id="min_factor", type="track", val=2, min=0, max=10, step=0.1, def=0.5 },
      { id="max_factor", type="track", val=2, min=0, max=10, step=0.1, def=1 },
      { id="extra_large_mag_ammo", type="track", val=2, min=0, max=5, step=0.1, def=0.7 },
      { id="extra_belt_mag_ammo", type="track", val=2, min=0, max=5, step=0.1, def=0.4 },
      { id="extra_db_ammo", type="track", val=2, min=0, max=5, step=0.1, def=2.5 },
      { id="extra_rifle_ammo", type="track", val=2, min=0, max=5, step=0.1, def=2 },
      { id="min_gl_ammo", type="track", val=2, min=0, max=10, step=1, def=0 },
      { id="max_gl_ammo", type="track", val=2, min=0, max=10, step=1, def=2 }
      --{ id="stash_min_factor", type="track", val=2, min=1, max=20, step=1, def=4 },
      --{ id="stash_max_factor", type="track", val=2, min=1, max=20, step=1, def=6 },
  }}, "dph_loot_cond"
end