local to_del = {
 ["hunter_gar_trader"] = true,
 ["baraholka_trader"] = true,
 --["baraholka_trader_night"] = true,
 ["esc_main_base_trader_mlr"] = true,
 ["esc_smart_terrain_5_7_loner_mechanic_stalker"] = true,
 ["trucks_cemetery_bandit_trader"] = true,
--  ["trucks_cemetery_bandit_mechanic"] = true,
}

function npc_on_net_spawn(npc)
  --printf("[oleh_despawner] init")
  if npc and to_del[npc:section()] then
    printf("[oleh_despawner] %s", npc:section())
    alife_release(npc)
  end
end

-- function main()
--   printf("[oleh_despawner] init")
--   for i = 1, 65534 do
--     local se_obj = alife_object(i)
--     if se_obj and IsStalker(se_obj) and to_del[se_obj:name()] then
--       printf("[oleh_despawner] %s", se_obj.se_obj:name())
--       alife_release(se_obj)
--     end
--   end
-- end

function on_game_start()
  RegisterScriptCallback("npc_on_net_spawn", npc_on_net_spawn)
end