-- allows to fire/reload weapon before draw animation completely ends
-- oleh5230, 11.05.26

-- To Do:
-- verify flag is attached to single draw anim
-- add key hold binds

local keybinds_whitelist = {
	[key_bindings.kWPN_FIRE] = true,
	[key_bindings.kWPN_ZOOM] = true,
	[key_bindings.kWPN_RELOAD] = true,
	[key_bindings.kWPN_FIREMODE_PREV] = true,
	[key_bindings.kWPN_FIREMODE_NEXT] = true,
	[key_bindings.kWPN_FUNC] = true,
	-- grenade launcher toggle key
	[key_bindings.kCUSTOM21] = true,
}

local nextTick = _G.nextTick or function(f, n)
	n = floor(max(n or 1, 1))
	AddUniqueCall(function()
		if n == 1 then
			return f()
		else
			n = n - 1
			return false
		end
	end)
end

local debug = false
local function print_dbg(txt, ...)
	if debug then printf("[oleh_fluid_weapon_draw] ".. txt, ...) end
end

local fluid_draw_flag = false
local fluid_draw_item_id = nil
function actor_on_hud_animation_play(anm_table, item)
	if item and IsWeapon(item)then
		fluid_draw_flag = false
		fluid_draw_item_id = nil
		if anm_table.anm_name and starts_with(tostring(anm_table.anm_name), "anm_show") then
			local sec = item:section()
			local id = item:id()
			local hud = ini_sys:r_string_ex(sec, "hud")
			local state = item:get_state()
			local length = hud and game.get_motion_length(hud, anm_table.anm_name, anm_table.anm_speed) or 500
			local length_mod = ini_sys:r_string_ex(sec,"draw_time_modifier") or 0.35
			print_dbg("[oleh_fluid_weapon_draw] anim start; flag: %s full length: %s, modified length: %s; state %s", fluid_draw_flag, length, length / 1000 * length_mod, state)
			if length and state and state == 1 and not fluid_draw_flag then
				CreateTimeEvent("fluid_weapon_draw", "fluid_draw_flag_enable", length / 1000 * length_mod,
				function()
					local active_item = db.actor:active_item()
					local active_item_state = active_item and active_item:get_state()
					if active_item and active_item:id() == id and
					active_item_state and active_item_state == 1 then
						print_dbg("[oleh_fluid_weapon_draw] enable flag")
						fluid_draw_flag = true
						fluid_draw_item_id = id
					end
					return true
				end, id)

				CreateTimeEvent("fluid_weapon_draw", "fluid_draw_flag_expire", length / 1000, function()
					fluid_draw_flag = false
					fluid_draw_item_id = nil
					print_dbg("[oleh_fluid_weapon_draw] expire flag")
					return true
				end, id)
			end
		end
	end
end

function on_before_key_press(key, bind)
	if keybinds_whitelist[bind] and fluid_draw_flag then
		local active_item = db.actor:active_item()
		local active_item_state = active_item and active_item:get_state()
		if active_item and IsWeapon(active_item) and not IsMelee(active_item) and
		active_item:id() == fluid_draw_item_id and active_item_state and active_item_state == 1 then
			if active_item:section() == "wpn_ks23_kaban" then return end
			print_dbg("![oleh_fluid_weapon_draw] switch state")
			active_item:switch_state(0)
			fluid_draw_flag = false
			fluid_draw_item_id = nil

			if bind == key_bindings.kWPN_ZOOM then
				if get_console():get_bool("wpn_aim_toggle") then
					level.press_action(key)
				else
					level.hold_action(key)
				end
			else
				nextTick(function() level.press_action(key) return true end)
			end
		end
	end
end

function on_game_start()
	RegisterScriptCallback("actor_on_hud_animation_play",actor_on_hud_animation_play)
	RegisterScriptCallback("on_before_key_press",on_before_key_press)
end