-- If you don't use MCM, change your defaults from here.
local defaults = {
    ["drop"] = 1
}

function get_config(key)
    return defaults[key]
end

function on_mcm_load()
    op = { id= "supgrades",sh=true ,gr={
            { id= "title",type= "slide",link= "ui_options_slider_player",text="ui_mcm_supgrades_title",size= {512,50},spacing= 20 },
            {id = "drop", type = "track", val = 2, min=20,max=100,step=1, def = 30},
        }
    }
    return op
end