
local rad_removed
actor_effects.Update_Rad = function(actor)
	-- if (not opt.enable_radiation_effect) then
	-- 	if (not rad_removed) then
	-- 		rad_removed = true
	-- 		level.remove_pp_effector(2020)
	-- 	end
	-- 	return
	-- end
	-- rad_removed = false
	
	-- local radiation = actor.radiation
	-- if (radiation > 0) then
	-- 	if (radiation > opt.radiation_ppe_threshold) then
	-- 		level.add_pp_effector("radiation.ppe", 2020, true)
	-- 	else
	-- 		level.remove_pp_effector(2020)
	-- 	end
	-- 	level.set_pp_effector_factor(2020, radiation)
	-- 	if (math.random() < radiation) then
	-- 		radiation = (radiation > 0.5) and (math.random() < radiation/1.3) and "click3" or math.random(8)
	-- 		local snd = sound_object("detectors\\geiger_" .. radiation)
	-- 		snd:play(actor, 0, sound_object.s2d)
	-- 	end
	-- end
end
